BankaOtomasyon/Controllers/HesapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BankaOtomasyon.Models;

namespace BankaOtomasyon.Controllers
{
    [LoginController]
    public class HesapController : Controller
    {
        private BankaDBEntities db = new BankaDBEntities();
        // GET: Hesap
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult HesapOlustur()
        {
            
            int b = Convert.ToInt32(Session["musteriId"]);
            var model = db.tblMusteriHesap.FirstOrDefault(i => i.musteriId == b);
            return View(model);
        }

        [HttpGet]
        public ActionResult EkHesapOlustur()
        {
            string message = "";
            var hesap = new tblMusteriHesap();


            int a = Convert.ToInt32(Session["musteriHesapNo"]);
            int b = Convert.ToInt32(Session["musteriId"]);
            hesap.hesapNumarasi = a;
            hesap.musteriId = Convert.ToInt32(Session["musteriId"]);
            hesap.hesapAcilisTarihi = DateTime.Now;
            hesap.hesapAcikMi = true;
            hesap.hesapBakiye = 0;
            hesap.hesapEkNumarasi = HesapEkNo();
            var result = db.tblMusteriHesap.Add(hesap);


            if (result != null)
            {
                db.SaveChanges();
                return RedirectToAction("HesapOlustur");
            }

            return View();
        }


        public int HesapEkNo()
        {
            int a = (int)Session["musteriId"];
            var q = db.tblMusteriHesap.FirstOrDefault(i => i.musteriId == a);
            if (q == null)
            {
                return 5001;
            }
            else
            {
                int? b = db.tblMusteriHesap.Where(i => i.musteriId == a).Max(i => i.hesapEkNumarasi);
                int ekno = Convert.ToInt32(b + 1);
                return ekno;
            }

        }

        public PartialViewResult _tblHesap()
        {
            int a = Convert.ToInt32(Session["musteriId"]);
            var model = db.tblMusteriHesap.Where(i => i.musteriId == a).ToList();
            return PartialView("_tblHesap", model);

        }

        public ActionResult HesapKapat(int? id)
        {
            string bakiye = "";
            tblMusteriHesap hesap = db.tblMusteriHesap.Find(id);
            hesap.hesapAcikMi = false;
            hesap.hesapKapanisTarihi = DateTime.Now;
            if (ModelState.IsValid && hesap.hesapBakiye==0)
            {
                db.Entry(hesap).State = EntityState.Modified;
                db.SaveChanges();

            }
            else
            {
                bakiye = "Hesabinizi kapatmak icin bakiyeniz olmamalidir";
                TempData["bakiye"] = bakiye;
            }
            return RedirectToAction("HesapOlustur");
        }

        [HttpPost]
        public ActionResult HesapParaYatir([Bind(Include = "HesapEkNo,Para")]HesapParaModel model)
        {
            int mID = Convert.ToInt32(Session["musteriId"]);
            if (ModelState.IsValid)
            {
                db.ParaYatir(model.Para, model.HesapEkNo,mID);
                return RedirectToAction("HesapOlustur");
            }

            return View();
        }

        [HttpGet]
        public ActionResult HesapParaYatir()
        {
            int mID = Convert.ToInt32(Session["musteriId"]);
            var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);
            ViewBag.HesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            return View();
        }
        [HttpGet]
        public ActionResult HesapParaCek()
        {
            int mID = Convert.ToInt32(Session["musteriId"]);
            var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);
            ViewBag.HesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            return View();
        }

        [HttpPost]
        public ActionResult HesapParaCek([Bind(Include = "HesapEkNo,Para")]HesapParaModel model)
        {
            int mID = Convert.ToInt32(Session["musteriId"]);
            int hesap = model.HesapEkNo;
            var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);
            string message = "";
            var max = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapEkNumarasi == hesap).Max(i => i.hesapBakiye);
            if (ModelState.IsValid && model.Para <= max)
            {
                db.ParaCek(model.Para, model.HesapEkNo,mID);
                return RedirectToAction("HesapOlustur");
            }
            else
            {
                ViewBag.message = "Hesabinizda yeterli miktar yok!";
            }

            ViewBag.HesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            return View(model);
        }
    }
}

BankaOtomasyon/Views/Hesap/HesapOlustur.cshtml
@{
    ViewBag.Title = "HesapOlustur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 
<div class="app-main__outer">
    <div class="app-main__inner">
         
    <div class="">
           
            <div class="row">
                <div class="col-lg-6 col-xl-4">
                    <div class="card mb-3 widget-content bg-night-fade">
                        <div class="widget-content-wrapper text-white">
                            <div class="widget-content-left">
                                <div class="widget-heading">@Session["musteriFullName"]</div>
                                <div class="widget-subheading">Müşteri Numarası</div>
                            </div>
                            <div class="widget-content-right">
                                <div class="widget-numbers text-white"><span>@Session["musteriHesapNo"]</span></div>
                                <button class="mb-2 mr-2 btn btn-light" onclick="window.location.href='/Hesap/EkHesapOlustur'">Hesap Aç
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                @{Html.RenderAction("_tblHesap", "Hesap");}
            </div>
            
      
        </div>
    </div>
    
</div>
 
 

BankaOtomasyon/Views/Hesap/HesapParaCek.cshtml
 @model BankaOtomasyon.Models.HesapParaModel
@{
    ViewBag.Title = "HesapParaCek";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="app-main__outer">
    <div class="app-main__inner">

        <div class="">

            <div class="row">
                <div class="col-md-6">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Hesaptan  Para Cek</h5>
                            <form class="" method="post" action="">
                                @if (@ViewBag.message != null)
                                {
                                    <div class="alert alert-danger fade show" role="alert">@ViewBag.message</div>
                                }

                                <div class="position-relative form-group">
                                    <label for="exampleSelect" class="">Cekilcek Hesap Seçiniz</label>
                                    @Html.DropDownList("HesapEkNo", null, "--Para Cekilcek Hesap--", new { @class = "form-control" })
                                </div>

                                @Html.EditorFor(model => model.Para, new { htmlAttributes = new { @class = "mb-2 form-control", @onkeypress = "return event.charCode>= 48 &&event.charCode<= 57", @placeholder = "Yatırılacak Tutar" } })
                                <button class="mt-1 btn btn-primary" type="submit">Para Cek</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>

BankaOtomasyon/Views/Hesap/HesapParaYatir.cshtml
@model BankaOtomasyon.Models.HesapParaModel
@{
    ViewBag.Title = "HesapParaYatir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 
<div class="app-main__outer">
    <div class="app-main__inner">
         
        <div class="">
           
            <div class="row">
                <div class="col-md-6">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Hesaba Para Yatir</h5>
                            <form class="" method="post" action="">
                                
                                <div class="position-relative form-group">
                                    <label for="exampleSelect" class="">Yatırılcak Hesap Seçiniz</label>
                                    @Html.DropDownList("HesapEkNo", null,"--Para Yatırılacak Hesap--",new{@class="form-control"})
                                </div>
                                 
                                @Html.EditorFor(model => model.Para, new { htmlAttributes = new { @class = "mb-2 form-control",@onkeypress= "return event.charCode>= 48 &&event.charCode<= 57",@placeholder = "Yatırılacak Tutar" } })
                                <button class="mt-1 btn btn-primary"  type="submit">Para Yatir</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
      
        </div>
    </div>
    
</div>

BankaOtomasyon/Views/Hesap/_tblHesap.cshtml
@model IEnumerable<BankaOtomasyon.Models.tblMusteriHesap>

<div class="col-lg-6">
    <div class="main-card mb-3 card">
        <div class="card-body">
            <h5 class="card-title">Hesap Bilgileri</h5>
            @if (TempData["bakiye"] != null)
            {
                <div class="alert alert-danger fade show" role="alert">@TempData["bakiye"]</div>
            }
            <table class="mb-0 table table-striped">

                <thead>
                    <tr>
                        <th>#</th>
                        <th>HesapEkNo</th>
                        <th>Hesap Acilis Tarihi</th>
                        <th>Bakiye</th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    if (item.hesapAcikMi == true)
                    {
                        <tbody>
                            <tr>
                                <th scope="row"></th>
                                <td>@item.hesapEkNumarasi</td>
                                <td>@item.hesapAcilisTarihi.Value.Date.ToString("d")</td>
                                <td>@item.hesapBakiye</td>
                                <td>
                                    <button onclick="window.location.href='/Hesap/HesapKapat/@item.hesapId'" class="mb-2 mr-2 btn btn-danger">
                                        Kapat
                                    </button>
                                </td>
                            </tr>

                        </tbody>
                    }

                }
            </table>

        </div>
    </div>
</div>