BankaOtomasyon/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime.Misc;
using BankaOtomasyon.Models;
using PagedList;

namespace BankaOtomasyon.Controllers
{
    [LoginController]
    public class TransferController : Controller
    {
        private BankaDBEntities db=new BankaDBEntities();
        // GET: Transfer
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Virman()
        {
            int mID = Convert.ToInt32(Session["musteriId"]);
            var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);
            
            ViewBag.GonderenHesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            ViewBag.AliciHesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            return View();
        }
        [HttpPost]
        public ActionResult Virman([Bind(Include = "GonderilenBakiye,GonderenHesapEkNo,AliciHesapEkNo")]VirmanModel model)
        {
            int? a = Convert.ToInt32(Session["musteriHesapNo"]);
            int? b = model.GonderenHesapEkNo;
            int? c = model.GonderilenBakiye;
            int? d = model.AliciHesapEkNo;
            DateTime tarih=DateTime.Now;
            var bakiye = db.tblMusteriHesap.Where(i => i.hesapEkNumarasi == b && i.hesapNumarasi == a)
                .Max(i => i.hesapBakiye);
            if (ModelState.IsValid && bakiye>=c)
            {
                db.VirmanKaydet(d, b, c, a, tarih);
                db.Virman(d, b, c, a);
                return RedirectToAction("HesapOlustur", "Hesap");
            }
            else
            {
                int mID = Convert.ToInt32(Session["musteriId"]);
                string message = "";
                message = "Hesabınızda yeterli miktara para yok isleminiz gerçekleştirelemiyor!";
                ViewBag.message = message;
                var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);
                ViewBag.AliciHesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
                ViewBag.GonderenHesapEkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            }

            return View();
        }


        public JsonResult aliciDoldur(int GonderenHesapEkNo)
        {
            db.Configuration.ProxyCreationEnabled = false;
            int a = Convert.ToInt32(Session["musteriHesapNo"]);
            
            var model = db.Doldur(GonderenHesapEkNo, a).Where(i=>i.hesapAcikMi==true);
         
            return Json(model.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult bakiyeDoldur(int GonderenHesapEkNo)
        {
            db.Configuration.ProxyCreationEnabled = false;
            int a = Convert.ToInt32(Session["musteriHesapNo"]);

            var model = db.tblMusteriHesap.Where(i => i.hesapNumarasi == a && i.hesapEkNumarasi == GonderenHesapEkNo);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public JsonResult bakiyeGetir(int EkNo)
        {
            db.Configuration.ProxyCreationEnabled = false;
            int a = Convert.ToInt32(Session["musteriHesapNo"]);

            var model = db.tblMusteriHesap.Where(i => i.hesapNumarasi == a && i.hesapEkNumarasi == EkNo);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Havale()
        {
            int mID = Convert.ToInt32(Session["musteriId"]);
            var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);

            ViewBag.EkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
            return View();
        }
        [HttpPost]
        public ActionResult Havale([Bind(Include = "EkNo,bakiye,AliciHesapNo,AliciHesapEkNo")]HavaleModel model)
        {

            int? a = Convert.ToInt32(Session["musteriHesapNo"]);
            decimal? b = model.bakiye;
            int? c = model.AliciHesapNo;
            int? d = model.AliciHesapEkNo;
            int e = model.EkNo;
            DateTime tarih = DateTime.Now;
            var bakiye = db.tblMusteriHesap.Where(i => i.hesapEkNumarasi == e && i.hesapNumarasi == a)
                .Max(i => i.hesapBakiye);
            var hesap = db.tblMusteriHesap.FirstOrDefault(i => i.hesapNumarasi == a);
            if (ModelState.IsValid && bakiye >= b)
            {
                if (Kontrol(c, d)==true)
                {
                    
                        db.Havale(a, b, c, e, d);
                        db.HavaleKaydet(d, e, b, c, a, tarih);
                        return RedirectToAction("HesapOlustur", "Hesap");
                   
                }
                else
                {
                    string message = "";
                    message = "Kayitli hesap bulunamadi";
                    ViewBag.message = message;
                    int mID = Convert.ToInt32(Session["musteriId"]);
                    var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);


                    ViewBag.EkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi");
                }
                
            }
            else
            {
                
                string message = "";
                message = "Hesabınızda yeterli miktara para yok isleminiz gerçekleştirelemiyor!";
                ViewBag.message = message;
                int mID = Convert.ToInt32(Session["musteriId"]);
                var query = db.tblMusteriHesap.Where(i => i.musteriId == mID && i.hesapAcikMi == true);


                ViewBag.EkNo = new SelectList(query, "hesapEkNumarasi", "hesapEkNumarasi"); 
            }

            return View();
        }

        public bool Kontrol(int? hesapNo, int? ekNo)
        {
            int mID = Convert.ToInt32(Session["musteriHesapNo"]);
            if (hesapNo == mID)
            {
                return false;
            }
            else
            {
                var model = db.tblMusteriHesap.FirstOrDefault(i => i.hesapNumarasi == hesapNo && i.hesapEkNumarasi == ekNo && i.hesapAcikMi == true);

                return model != null;
            }

            
        }

        public ActionResult İslemTablosu(int? SayfaNo)
        {
            int _sayfaNo = SayfaNo ?? 1;
            var model=new CokluModel();
            int? a = Convert.ToInt32(Session["musteriHesapNo"]);
            model.TblHavales = db.tblHavale.Where(i => i.havaleGonderenHesapNo == a).ToList().ToPagedList(_sayfaNo,5);
            model.TblVirmans = db.tblVirman.Where(i => i.hesapNumarasi == a).ToList().ToPagedList(_sayfaNo,5);
             
            return View(model);
        }
    }
}

BankaOtomasyon/Views/Transfer/Havale.cshtml
@model BankaOtomasyon.Models.HavaleModel
@{
    ViewBag.Title = "Havale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="app-main__outer">
    <div class="app-main__inner">

        <div class="">

            <div class="row">
                <div class="col-md-6">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Virman Islemleri<div id="bakiyeGetir" class="ml-auto badge badge-pill badge-danger pull-right"></div></h5>

                            <form class="" method="post" action="">
                                <div id="ex">
                                    <div class="position-relative form-group">
                                        @if (ViewBag.message != null)
                                        {
                                            <div class="alert alert-danger fade show" role="alert">@ViewBag.message</div>
                                        }
                                        <label for="exampleSelect" class="">Gonderen Hesap Numarasi</label>

                                        @Html.DropDownList("EkNo", null, "--Ek Numaranizi Seciniz--", new { @class = "form-control" })
                                    </div>
                                    <div class="position-relative form-group">
                                        <label for="exampleSelect" class="">Alıcı Hesap Numarasi</label>
                                        @Html.EditorFor(model => model.AliciHesapNo, new { htmlAttributes = new { @class = "mb-2 form-control", @onkeypress = "return event.charCode>= 48 &&event.charCode<= 57", @placeholder = "Alici Hesap Numarasi" } })

                                    </div>
                                    <div class="position-relative form-group">
                                        <label for="exampleSelect" class="">Alıcı Hesap Ek Numarasi</label>
                                        @Html.EditorFor(model => model.AliciHesapEkNo, new { htmlAttributes = new { @class = "mb-2 form-control", @onkeypress = "return event.charCode>= 48 &&event.charCode<= 57", @placeholder = "Alici Hesap Ek Numarasi" } })

                                    </div>
                                </div>

                                @Html.EditorFor(model => model.bakiye, new { htmlAttributes = new { @class = "mb-2 form-control", @onkeypress = "return event.charCode>= 48 &&event.charCode<= 57", @placeholder = "Göderilcek Tutar" } })
                                <button class="mt-1 btn btn-primary" type="submit">Para Yatir</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>

BankaOtomasyon/Views/Transfer/Virman.cshtml
@model BankaOtomasyon.Models.VirmanModel
@{
    ViewBag.Title = "Virman";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="app-main__outer">
    <div class="app-main__inner">

        <div class="">

            <div class="row">
                <div class="col-md-6">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Virman Islemleri<div id="bakiye" class="ml-auto badge badge-pill badge-danger pull-right"></div></h5>
                             
                            <form class="" method="post" action="">
                                <div id="ex">
                                    <div class="position-relative form-group">
                                        @if (ViewBag.message != null)
                                        {
                                            <div class="alert alert-danger fade show" role="alert">@ViewBag.message</div>
                                        }
                                        <label for="exampleSelect" class="">Gonderen Hesap</label>

                                        @Html.DropDownList("GonderenHesapEkNo", null, "--Gönderilcek Hesap Seciniz--", new { @class = "form-control" })
                                    </div>
                                    <div class="position-relative form-group">
                                        <label for="exampleSelect" class="">Alıcı Hesap</label>

                                        @Html.DropDownList("AliciHesapEkNo", new SelectList(new SelectList(string.Empty)), "--Alıcı Hesap Seciniz--", new { @class = "form-control" })
                                    </div>
                                </div>
                                @Html.EditorFor(model => model.GonderilenBakiye, new { htmlAttributes = new { @class = "mb-2 form-control", @onkeypress = "return event.charCode>= 48 &&event.charCode<= 57", @placeholder = "Yatırılacak Tutar" } })
                                <button class="mt-1 btn btn-primary" type="submit">Para Yatir</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>

BankaOtomasyon/Views/Transfer/İslemTablosu.cshtml
@using PagedList.Mvc
@model BankaOtomasyon.Models.CokluModel
@{
    ViewBag.Title = "İslemTablosu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="app-main__outer">
    <div class="app-main__inner">
         
        <div class="">

            <div class="row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Virman İslemlerim</h5>

                            <table class="mb-0 table table-striped">

                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Hesap Numarasi</th>
                                        <th>Gonderen Ek Numarasi</th>
                                        <th>Alici Ek Numarasi</th>
                                        <th>Gonderilen Tarih</th>
                                        <th>Gonderilen Bakiye</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model.TblVirmans)
                                {

                                    <tbody>
                                        <tr>
                                            <th scope="row"></th>
                                            <td>@item.hesapNumarasi</td>
                                            <td>@item.gonderenEkNumarasi</td>
                                            <td>@item.aliciEkNumarasi</td>
                                            <td>@item.gonderilenTarih</td>
                                            <td>@item.gonderilenbakiye</td>
                                        </tr>

                                    </tbody>


                                }
                            </table>
                            <hr />
                            @Html.PagedListPager(Model.TblVirmans, _sayfaNo => Url.Action("İslemTablosu", "Transfer", new { SayfaNo = _sayfaNo }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< İlk", LinkToPreviousPageFormat = "< Önceki", LinkToNextPageFormat = "Sonraki >", LinkToLastPageFormat = "Son >>" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Havale İslemlerim</h5>

                            <table class="mb-0 table table-striped">

                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Gonderen Hesap Numarasi</th>
                                        <th>Gonderen Ek Numarasi</th>
                                        <th>Alici Hesap Numarasi</th>
                                        <th>Alici Ek Numarasi</th>
                                        <th>Havale Tarihi</th>
                                        <th>Gonderilen Bakiye</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model.TblHavales)
                                {

                                    <tbody>
                                        <tr>
                                            <th scope="row"></th>
                                            <td>@item.havaleGonderenHesapNo</td>
                                            <td>@item.havaleGonderenEkNo</td>
                                            <td>@item.havaleAliciHesapNo</td>
                                            <td>@item.havaleAliciEkNo</td>
                                            <td>@item.havaleTarih</td>
                                            <td>@item.bakiye</td>

                                        </tr>

                                    </tbody>


                                }
                            </table>
                            <hr />
                            @Html.PagedListPager(Model.TblHavales, _sayfaNo => Url.Action("İslemTablosu", "Transfer", new { SayfaNo = _sayfaNo }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< İlk", LinkToPreviousPageFormat = "< Önceki", LinkToNextPageFormat = "Sonraki >", LinkToLastPageFormat = "Son >>" })
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
    
</div>